### PR TITLE
Revert invalid commit

### PR DESCRIPTION
**Pull request by lt-name**

### CODE REVIEW

**Comment by Buddelbubi** [comment]
Im freaking our rn...

**Comment by Buddelbubi** [comment]
Dont merge this please!

**Comment by lt-name** [comment]
> Dont merge this please!

People using wdpe can manually turn off experimental mode
This change is to allow the repaired version of wdpe to use experimental mode normally

Compatible with experimental mode wdpe: https://ci.lanink.cn/job/WaterdogPE/job/mot/

**Comment by Buddelbubi** [comment]
But custom blocks cannot be registered without experiment mode.

**Pull request closed without merging**
