### PR TITLE
PNX启动器

### PR DESCRIPTION
**Pull request by Superice666**
PNX启动器（bootstrap）是用来快捷方便地启动pnx并自动配置环境的程序

### CODE REVIEW

**Comment by chencu5958** [comment]
PNX启动器有考虑多语言不

**Comment by smartcmd** [comment]
> Hello PNX Team
> 
> Sorry but, Many Users have now Testing this Software a few days with all Plugin from Cloudburst. 60 Percent of Plugins doenst work because Incompatible Java Version.
> 
> Yes, Java is Backwards compatible (PetteriM1) say this, but its Not working.
> 
> You should create Java 8 Version because all Plugins are working and Java 8 is supported for year 2030!
> 
> Java 8 is Most used Version. A Server Software without Plugin compatibility is useless.

I don't know where you got the number 60%......

**Comment by PocketMiner92** [comment]
Simple Mathematics

**Comment by smartcmd** [comment]
> 

:D

**Comment by Superice666** [comment]
@PocketMiner92 @smartcmd We should open an issue to discuss this instead of discussing here

**Comment by PocketMiner92** [comment]
Yes its better.
But you should try Many Plugins Like Fawe, Plotsquared, Multiworld, Worldmanager, DBlib, KotlinLib and Many More.
All These Important Plugins doenst work.

**Comment by smartcmd** [comment]
> @PocketMiner92 @smartcmd We should open an issue to discuss this instead of discussing here

right, bug i prefer discussing in dc server

**Comment by PocketMiner92** [comment]
Error: LinkageError occurred while loading main class cn.nukkit.Nukkit

java.lang.UnsupportedClassVersionError: cn/nukkit/Nukkit has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0

You cant Install this in Gameservers.

**Comment by chencu5958** [comment]
> Error: LinkageError occurred while loading main class cn.nukkit.Nukkit
> 
> java.lang.UnsupportedClassVersionError: cn/nukkit/Nukkit has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
> 
> You cant Install this in Gameservers.

Maybe you need to take a look at our [official documentation](https://doc.powernukkitx.cn/en-us/faq/Server_faq.html)

**Comment by PocketMiner92** [comment]
Now Java 17

Error: Unable to initialize main class cn.nukkit.Nukkit

Caused by: java.lang.NoClassDefFoundError: joptsimple/OptionSpec

**Comment by Superice666** [comment]
> Now Java 17
> 
> Error: Unable to initialize main class cn.nukkit.Nukkit
> 
> Caused by: java.lang.NoClassDefFoundError: joptsimple/OptionSpec

You didn't link libraries. Add classpath argument or use bootstrap to start your server.
(Google before asking)

**Comment by PocketMiner92** [comment]
Its a Gameserver.
You cant Change Many Things manually.
 (Google can Help you)

**Comment by Superice666** [comment]
> Its a Gameserver. You cant Change Many Things manually. (Google can Help you)

So use jars on master branch to solve this problem if you cant download the bootstrap.jar and double-click or use `java -jar bootstrap.jar`.

**Comment by PocketMiner92** [comment]
Have fun with These Shit 
Useless Chinese Bullshit

Please Ban me from this Buggy Shit!

**Comment by Superice666** [comment]
@PocketMiner92 
We have seen a lot of anti-Chinese people, but we believe that technology knows no borders, so we still treat everyone, including anti-Chinese people, with equal respect.
We are disappointed by your use of insulting terms, and although PNX is not a very well developed project, we will continue to develop it as we have set out to do. Thank you for your support.

**Comment by jargod520** [comment]
Dear author, please don't care what PocketMiner92 says. He's just a little ruffian looking for a sense of existence. Although your work has some defects for the time being, it is still done very well. I will always support you

**Comment by TobidieTopfpflanze** [comment]
> Dear author, please don't care what PocketMiner92 says. He's just a little ruffian looking for a sense of existence. Although your work has some defects for the time being, it is still done very well. I will always support you

Yep, he leaves a lot of comments on other Minecraft related projects without any understanding how much work you have to put in such projects or how those things are managed internally. He wants everything and every feature working out of the box. At least that's the impression he gives me.

**Pull request merged**
