### PR TITLE
Codecov update config

### PR DESCRIPTION
**Pull request by AzaleeX**

### CODE REVIEW

**Comment by AzaleeX** [comment]
do not accept immediately

**Comment by smartcmd** [comment]
Why remove comments?

**Comment by AzaleeX** [comment]
because I'm done

**Comment by smartcmd** [comment]
> because I'm done

I may not have expressed myself clearly. I would like to ask why the code comments were deleted.

**Comment by AzaleeX** [comment]
I can put them back if I really need to, but for example the //deop comment doesn't need to be there.

**Comment by smartcmd** [comment]
You'd better add them back

**Comment by smartcmd** [comment]
By the way, you need to standardize your commit message, I've never seen this format before

**Comment by smartcmd** [comment]
type(range): message

**Pull request merged**
