### PR TITLE
1.20 features & 1.20.40 fixes

### PR DESCRIPTION
**Pull request by KoshakMineDEV**
- Bamboo now can be placed on moss block like in vanilla
- Sugarcane now can be placed on podzol and moss block like in vanilla
- Torchflower is working properly and can be placed in flower pot
- Added Torchflower Seeds and Torchflower crop now works like in vanilla
- Fixed ancient debris id in the BlockID class
- Fixed Ender Portal Frame placing
- Fixed Mangroove Roots placing
- Sniffer egg default state is no_cracks
- Decorated Pot no more disappearing #1408
- Fixed Pink Petals placing
- Added all Pottery Sherds
- Pottery Sherds placing on Decorated pot
- Fixed Campfire & Soul Campfire placing

### CODE REVIEW

**Comment by KoshakMineDEV** [comment]
I think latest commit fixed issue #1408. Needs more tests from other people

**Comment by KoshakMineDEV** [comment]
Currently I'm developing system for placing sherds on Decorated Pot. 
image

**Comment by Mcayear** [comment]
> I think latest commit fixed issue #1408. Needs more tests from other people

Tested and valid.

**Comment by KoshakMineDEV** [comment]
I'm not sure that PR is ready to merge. I wanna add brush and make suspicious sand and gravel working. But I can do that in other pr, and if you want - you can merge it

**Comment by KoshakMineDEV** [comment]
I think i will do this in other pr. Changed state to ready for review

**Review by smartcmd — APPROVED** [review]

**Pull request merged**
