### PR TITLE
Block Entity Bug fixed!

### PR DESCRIPTION
**Pull request by Buddelbubi**
I guess I finally made it... It was so.. It took at least 6 hours of testing and fixing.. 
But at some point, I managed to get rid of the **Could not create a block entity of type {} with x args** message by finding the cause and fixing it.

### CODE REVIEW

**Comment by Buddelbubi** [comment]
I swear I will create a new fork after this...

**Review by AzaleeX — COMMENTED** [review]
for now it seems ok to me if you add something / an extra commit if you can mention me 😎

**Review by CoolLoong — APPROVED** [review]

**Comment by smartcmd** [comment]
It looks like there are some backward-breaking changes. Should have more tests

**Comment by Buddelbubi** [comment]
What should I look for? I installed this on syodo to check if there are any problems in the long terms.

**Pull request merged**
