### PR TITLE
初步完成实体AI架构

### PR DESCRIPTION
**Pull request by Superice666**
实体AI架构已经初步完成
- [x] 寻路器接口
  - [x] 启发式A*寻路器
- [x] 智能实体类
- [x] 实体目标接口
- [x] 实体控制接口

此pr还附带初步实现了绵羊乞食跟随的AI作为示例。

### CODE REVIEW

**Review by PocketMiner92 — COMMENTED** [review]
PowernukkitX should learn to write only English Titles.
This is why noone use this.
English Community is much bigger.
Noone use this and havent any Plan whats happened Here.

**Comment by Superice666** [comment]
> PowernukkitX should learn to write only English Titles. This is why noone use this. English Community is much bigger. Noone use this and havent any Plan whats happened Here.

That's also why few Chinese use nukkit. Google translate may help you.

**Comment by smartcmd** [comment]
> PowernukkitX should learn to write only English Titles. This is why noone use this. English Community is much bigger. Noone use this and havent any Plan whats happened Here.

You are right, so we use Chinese

**Comment by smartcmd** [comment]
> PowernukkitX should learn to write only English Titles. This is why noone use this. English Community is much bigger. Noone use this and havent any Plan whats happened Here.

太对啦哥

**Review by zimzaza4 — COMMENTED** [review]
是否可以添加EntityJumpEvent?

**Comment by lt-name** [comment]
寻路对于草方块的判断好像有点问题，遇到草也会跳跃

**Comment by Superice666** [comment]
> 寻路对于草方块的判断好像有点问题，遇到草也会跳跃

你是指平地上把草当成固体方块跳跃吗？（群里有个视频里面没有这样啊）

**Comment by Ootmnt150oO** [comment]
不合併進去主分支嗎?

**Comment by CoolLoong** [comment]
> 不合併進去主分支嗎?

没完成，还有bug

**Pull request closed without merging**
