### PR TITLE
Fix empty chunk sections

### PR DESCRIPTION
**Pull request by KCodeYT**

### CODE REVIEW

**Review by Superice666 — CHANGES_REQUESTED** [review]
In many cases, chunk sections also need to preserve biome data. For example, the biomes in nether.

**Comment by KCodeYT** [comment]
> In many cases, chunk sections also need to preserve biome data. For example, the biomes in nether.

But then they are not empty they contain biome data

**Comment by Superice666** [comment]
> But then they are not empty they contain biome data

I think that empty just means that they contain no blocks. Containing biome data is necessary for each ChunkSection.

**Comment by KCodeYT** [comment]
> > But then they are not empty they contain biome data
> 
> I think that empty just means that they contain no blocks. Containing biome data is necessary for each ChunkSection. Just imagine that you are build a high building in the_end, and when you get to its top, finding that the sun is shining because the empty chunksection contains no biome data.

Hmm I think the copy last flag should be used for empty chunk sections

**Pull request closed without merging**
