### PR TITLE
Refactoring SetEntityLinkPacket

### PR DESCRIPTION
**Pull request by Dhaiven**
- Add `Builder` static class in `SetEntityLinkPacket` class to remove rededant code
- Create enum `EntityLink.Type` to replace const in `SetEntityLinkPacket`

### CODE REVIEW

**Comment by CoolLoong** [comment]
Directly access the fields of the datapacket is the design style of PNX, and I don't want to change it

**Comment by Dhaiven** [comment]
why you don't want to change it ?

**Comment by CoolLoong** [comment]
Keep the usage of each packet the same, rather than each different one

**Comment by KoshakMineDEV** [comment]
Just change all fields in datapackets to private and make them accessible with get and set. Direct field access is not good

**Comment by Dhaiven** [comment]
> Conservez la même utilisation de chaque paquet, plutôt que de chacun d’entre eux

I agree, but for enumeration, there are packages like camera that use enumeration. However, I agree that the build class is probably useless.

**Comment by CoolLoong** [comment]
Enum is useful, you can keep it

**Comment by Dhaiven** [comment]
ok so i revert the builder change

**Comment by Dhaiven** [comment]
It's okay, I've finally made it

**Comment by CoolLoong** [comment]
You can directly remove this old method

**Comment by Dhaiven** [comment]
All right

**Review by CoolLoong — APPROVED** [review]

**Pull request merged**
