### PR TITLE
Remove Timings and bundle Spark

### PR DESCRIPTION
**Pull request by alvin0319**
Since most Java softwares are about to remove Timings and bundle Spark, I think PNX should also be following these.

https://github.com/PaperMC/Paper/issues/8948

Reference: https://github.com/CloudburstMC/Nukkit/pull/2117

### CODE REVIEW

**Comment by smartcmd** [comment]
I support this idea

**Comment by alvin0319** [comment]
so let's just remove timings completely from the core?

**Comment by smartcmd** [comment]
Yes

**Comment by alvin0319** [comment]
Done, not sure about how to deal with remaining configurations related to Timings. (also new configuration)

**Comment by smartcmd** [comment]
Look like there are a lot of tests need to be fixed :(

**Comment by alvin0319** [comment]
Waiting https://github.com/PowerNukkitX/PowerNukkitX-JUnit5-Framework/pull/3 to be merged.

**Comment by SuperIceCN** [comment]
Since https://github.com/PowerNukkitX/PowerNukkitX-JUnit5-Framework/pull/3 is merged, is it possible to change back the dependencies to `cn.powernukkit`?

**Comment by alvin0319** [comment]
> Since [PowerNukkitX/PowerNukkitX-JUnit5-Framework#3](https://github.com/PowerNukkitX/PowerNukkitX-JUnit5-Framework/pull/3) is merged, is it possible to change back the dependencies to `cn.powernukkit`?

0.0.4 hasn't been released in maven central. or I can use commit hash (jitpack) if you want.

**Comment by SuperIceCN** [comment]
> > Since [PowerNukkitX/PowerNukkitX-JUnit5-Framework#3](https://github.com/PowerNukkitX/PowerNukkitX-JUnit5-Framework/pull/3) is merged, is it possible to change back the dependencies to `cn.powernukkit`?
> 
> 0.0.4 hasn't been released in maven central. or I can use commit hash (jitpack) if you want.

Maybe we can use 0.0.4 relaese with jitpack:

```xml
<dependency>
    <groupId>cn.powernukkitx</groupId>
    <artifactId>PowerNukkitX-JUnit5-Framework</artifactId>
    <version>0.0.4</version>
</dependency>

**Comment by alvin0319** [comment]
Done.

**Review by lt-name — APPROVED** [review]

**Pull request merged**
