### PR TITLE
refactor: command system

### PR DESCRIPTION
**Pull request by MEFRREEX**
Changes: 
1. Removed deprecated classes related to commands
2. Removed deprecated and unused methods
6. Removed deprecated methods Server#dispatchCommand and CommandMap#dispatch
3. Refactored CommandEnum class
4. Public fields replaced with getters and setters
5. Added method ParamList.getResult(int index, E defaultValue)

and some other changes

### CODE REVIEW

**Comment by CoolLoong** [comment]
I won't accept name refactoring, I can only accept modification 6

**Comment by MEFRREEX** [comment]
> I won't accept name refactoring, I can only accept modification 6

What do you mean? Changing names in CommandEnum?

**Comment by CoolLoong** [comment]
I mean, you shouldn't modify these field visibility, there is no difference between get setter and public

**Comment by MEFRREEX** [comment]
It doesn't affect the api in any way, but okay, I can revert those changes

**Comment by CoolLoong** [comment]
It affects compatibility and many plugins need to be modified. Mostly it's a pointless change

**Comment by MEFRREEX** [comment]
Okay, I'll revert this changes

**Comment by MEFRREEX** [comment]
Everything's okay now?

**Pull request merged**
