### PR TITLE
Reorganizes issues template

### PR DESCRIPTION
**Pull request by AzaleeX**
- Removal of Chinese language issue support (https://github.com/PowerNukkitX/PowerNukkitX/commit/227d6fcf17d0a43e80336c0e347e566342b1f775)
- Addition and revamp of the bug report issue template (https://github.com/PowerNukkitX/PowerNukkitX/commit/657293d90503804c5aa21f56c77b7267825f4aed)
- Addition of items in the template menu: (https://github.com/PowerNukkitX/PowerNukkitX/commit/9ae26aaec73c5b8d53a8165d4faa3219da1cda2d)
  > Documentation link
  > Discord server link

### Why are we gradually removing elements related to the Chinese language ?

In my perspective, `PowerNukkitX` should be international, therefore using a **language** that most people can understand and have a basic familiarity with (or else utilize a translator). However, it's important to make these changes, as while the software was initially created by you, users tend to prefer a **Minecraft Bedrock software that is more oriented towards languages such as English**.

**The next step would be removing Chinese names from the tags.**

### CODE REVIEW

**Comment by Mcayear** [comment]
I think it's a negative update because it's not good for multilingual projects.

The current issue template supporting Chinese and English does not conflict with the `international` goal. On the contrary, removing support for a language with the most users is not conducive to internationalization.
In addition, the number of native speakers of English is far less than that of chinese, and 80% of people who communicate in English may not be native English speakers.

To enhance development efficiency among code contributors and foster international development, we can implement the following measures:
- Unified `pull request` language to English.
- Standardize the 'pull request' tags, such as '(change)', '(fix)', '(delete)', and '(feat)'.
- Enhance the multi-language documentation of pnx.

**Comment by AzaleeX** [comment]
> I think it's a negative update because it's not good for multilingual projects.
> 
> The current issue template supporting Chinese and English does not conflict with the `international` goal. On the contrary, removing support for a language with the most users is not conducive to internationalization. In addition, the number of native speakers of English is far less than that of chinese, and 80% of people who communicate in English may not be native English speakers.
> 
> To enhance development efficiency among code contributors and foster international development, we can implement the following measures:
> 
> * Unified `pull request` language to English.
> * Standardize the 'pull request' tags, such as '(change)', '(fix)', '(delete)', and '(feat)'.
> * Enhance the multi-language documentation of pnx.

Yes, after this **pull request,** it only changes the `template` of the issues to prevent duplication between **English** and **Chinese**. 

So, I don't see a problem.

This pull request simply aims to do what you mentioned at the end, which is that everyone speaks in English. It's a restriction for someone like me who doesn't speak `Chinese`

**Comment by chencu5958** [comment]
I don't think this modification will have a significant impact on the template section, but rather will affect the internationalization of the project. However, I personally support the content added in [#9ae26aa](https://github.com/PowerNukkitX/PowerNukkitX/commit/9ae26aaec73c5b8d53a8165d4faa3219da1cda2d)

**Comment by AzaleeX** [comment]
I understand that you see an issue in this system, but as a developer at PowerNukkitX, for example, when I come across an issue written in Chinese, I sometimes struggle to translate what the real problem is. Anyway, it's a challenge for me.

If you want this system to be international, it would be necessary to include all the other languages like French, Spanish, Italian, and many others. In this regard, I don't see any downside to it, but it would result in duplicated issue templates.

I am absolutely not against

I just wish I had this system in place to make it easier to see the issues

**Comment by AzaleeX** [comment]
> I actually have a better idea for this, provided that you can provide permission to modify the PR. As long as it is in place, theoretically, it can completely achieve the coexistence of Chinese and English

I don't understand what you want to do

**Comment by chencu5958** [comment]
> > I actually have a better idea for this, provided that you can provide permission to modify the PR. As long as it is in place, theoretically, it can completely achieve the coexistence of Chinese and English
> 
> I don't understand what you want to do ?

I actually have a better idea for this, provided that you can provide permission to modify the PR. As long as it is in place, theoretically, it can completely achieve the coexistence of Chinese and English

**Comment by chencu5958** [comment]
> > I actually have a better idea for this, provided that you can provide permission to modify the PR. As long as it is in place, theoretically, it can completely achieve the coexistence of Chinese and English
> 
> I don't understand what you want to do ?

I actually have a better idea for this, provided that you can provide permission to modify the PR. As long as it is in place, theoretically, it can completely achieve the coexistence of Chinese and English

> > I actually have a better idea for this, provided that you can provide permission to modify the PR. As long as it is in place, theoretically, it can completely achieve the coexistence of Chinese and English
> 
> I don't understand what you want to do ?

You can understand it this way, can the assigned labels be described in English/Chinese? Similarly, I can also do this in the introduction title of the template. As for the content inside, it can be described in Chinese line by line in English

**Comment by chencu5958** [comment]
> > I actually have a better idea for this, provided that you can provide permission to modify the PR. As long as it is in place, theoretically, it can completely achieve the coexistence of Chinese and English
> 
> I don't understand what you want to do ?

You can understand it this way, can the assigned labels be described in English/Chinese? Similarly, I can also do this in the introduction title of the template. As for the content inside, it can be described in Chinese line by line in English

**Comment by chencu5958** [comment]
> > I actually have a better idea for this, provided that you can provide permission to modify the PR. As long as it is in place, theoretically, it can completely achieve the coexistence of Chinese and English
> 
> I don't understand what you want to do ?

This can solve the confusion caused by too many templates without affecting the reading of Chinese and English native speakers, which is more useful than this one size fits all approach

**Comment by AzaleeX** [comment]
> 

This is above all what you call the coexistence of Chinese English, this is not already done in the tags

**Comment by AzaleeX** [comment]
my goal in the end is that in the issue template there is the least possible choice because this creates duplicates

**Comment by AzaleeX** [comment]
the PR can still be modified because it has not been verified and then accepted so it can still have updates

**Comment by chencu5958** [comment]
> the PR can still be modified because it has not been verified and then accepted so it can still have updates

Okay, thank you. I'll make some modifications and improvements to it when I have time

**Comment by Mcayear** [comment]
I'm glad that we share the same idea of unifying the language used in `pull requests`. It means we both believe that English is more suitable for development.

However, this strategy may not be appropriate for `issues`, as it lead to **distorted information**.

You mentioned that while retaining a multilingual issue template, this strategy may lead to duplicated content within the issue. However, this does not hinder our ability to address the issues, so it may not provide sufficient grounds for us to delete chinese issue templates.

Objectively speaking, this will not affect the communication of English or Chinese issue. but hidden problem is that issues will accumulate too much.

My final suggestion is:
- I recommend adding **github bot** to close issues older than 60 days.
- I think we can make full use of github's [discussions](https:github.com/PowerNukkitX/PowerNukkitX/discussions) function to have planned and non-repetitive development content discussions, and we can make it a new English-only communication environment

**Comment by AzaleeX** [comment]
> I'm glad that we share the same idea of unifying the language used in `pull requests`. It means we both believe that English is more suitable for development.
> 
> However, this strategy may not be appropriate for `issues`, as it lead to **distorted information**.
> 
> You mentioned that while retaining a multilingual issue template, this strategy may lead to duplicated content within the issue. However, this does not hinder our ability to address the issues, so it may not provide sufficient grounds for us to delete chinese issue templates.
> 
> Objectively speaking, this will not affect the communication of English or Chinese issue. but hidden problem is that issues will accumulate too much.
> 
> My final suggestion is:
> 
> * I recommend adding **github bot** to close issues older than 60 days.
> * I think we can make full use of github's [discussions](https:github.com/PowerNukkitX/PowerNukkitX/discussions) function to have planned and non-repetitive development content discussions, and we can make it a new English-only communication environment

Hi 

`I think we can make full use of github's discussions function to have planned and non-repetitive development content discussions, and we can make it a new English-only communication environment`

I don't really understand what you were talking about earlier https://github.com/PowerNukkitX/PowerNukkitX/discussions

**Comment by AzaleeX** [comment]
I have already created a github bot to find out if the UnConfirmed label is on it https://github.com/PowerNukkitX/PowerNukkitX/pull/1366

**Review by AzaleeX — COMMENTED** [review]
ok I misunderstood what you want to do

**Comment by chencu5958** [comment]
> ok I misunderstood what you want to do

Can you understand what I'm doing now

**Pull request closed without merging**
